_format_version: "1.1"

services:
  - name: auth
    url: http://movabi-supabase-auth:8081
    routes:
      - name: auth
        paths:
          - /auth/v1

  - name: rest
    url: http://movabi-supabase-rest:3000
    routes:
      - name: rest
        paths:
          - /rest/v1

  - name: realtime
    url: http://movabi-supabase-realtime:4000
    routes:
      - name: realtime
        paths:
          - /realtime/v1