_format_version: "1.1"

services:
  - name: auth
    url: http://movabi-supabase-auth:9999
    routes:
      - name: auth
        paths:
          - /auth/v1

  - name: rest
    url: http://movabi-supabase-rest:3000
    routes:
      - name: rest
        paths:
          - /rest/v1

  - name: realtime
    url: http://movabi-supabase-realtime:4000
    routes:
      - name: realtime
        paths:
          - /realtime/v1

plugins:
  - name: cors
    config:
      origins:
        - http://localhost:3000
        - https://movabi.apps.evolsolution.com
      headers:
        - Accept
        - Accept-Language
        - Content-Language
        - Content-Type
        - Authorization
        - x-client-info
        - apikey
        - X-Client-Info
        - Range
        - Range-Unit
        - Content-Profile
        - Accept-Profile
        - Prefer
      methods:
        - GET
        - POST
        - PATCH
        - DELETE
        - OPTIONS
        - PUT
      exposed_headers:
        - Content-Range
        - X-Total-Count
        - Content-Profile
        - Accept-Profile
      max_age: 3600
      credentials: true
