import{CommonModule}from'@angular/common';import{Component,OnInit,inject,signal}from'@angular/core';import{FormsModule}from'@angular/forms';
import{AdminMarketAvailabilityService,MarketAvailabilityRow}from'../../services/admin-market-availability.service';
@Component({selector:'app-market-rollout',standalone:true,imports:[CommonModule,FormsModule],template:`
<main class="p-6 max-w-7xl mx-auto"><div class="flex justify-between"><div><h1 class="text-2xl font-bold">Market Rollout</h1><p class="text-slate-500">Backend-enforced country, city and zone capabilities.</p></div><button class="px-4 py-2 bg-blue-600 text-white rounded" (click)="create()">New scope</button></div>
<div class="grid lg:grid-cols-2 gap-5 mt-6"><section class="bg-white border rounded p-4"><table class="w-full text-sm"><thead><tr><th>Scope</th><th>Status</th><th>Quote</th><th></th></tr></thead><tbody>@for(row of rows();track row.id){<tr><td>{{row.country_code}} / {{row.market_city||'Country'}} / {{row.zone_id||'All zones'}}</td><td>{{row.launch_status}}</td><td>{{row.quote_enabled?'On':'Off'}}</td><td><button class="text-blue-600" (click)="edit(row)">Edit</button></td></tr>}</tbody></table></section>
@if(form()){<form class="bg-white border rounded p-5 grid grid-cols-2 gap-3" (ngSubmit)="save()"><label>Country<input name="country" maxlength="2" [(ngModel)]="form()!.country_code"></label><label>City<input name="city" [(ngModel)]="form()!.market_city"></label><label>Zone<input name="zone" [(ngModel)]="form()!.zone_id"></label><label>Status<select name="status" [(ngModel)]="form()!.launch_status">@for(s of statuses;track s){<option [value]="s">{{s}}</option>}</select></label>
<label>Currency<input name="currency" maxlength="3" [(ngModel)]="form()!.supported_currency"></label><label>Timezone<input name="timezone" [(ngModel)]="form()!.timezone"></label><label class="col-span-2">Title<input name="title" [(ngModel)]="form()!.unavailable_title"></label><label class="col-span-2">Message<textarea name="message" [(ngModel)]="form()!.unavailable_message"></textarea></label>
@for(c of capabilityFields;track c.key){<label><input type="checkbox" [name]="c.key" [(ngModel)]="form()![c.key]"> {{c.label}}</label>}<label>Valid from<input type="datetime-local" name="validFrom" [(ngModel)]="form()!.valid_from"></label><label><input type="checkbox" name="enabled" [(ngModel)]="form()!.enabled"> Active</label>
<button class="col-span-2 py-2 bg-blue-600 text-white rounded" type="submit">Save existing scope by ID</button></form>}</div></main>`})
export class MarketRolloutComponent implements OnInit{private api=inject(AdminMarketAvailabilityService);rows=signal<MarketAvailabilityRow[]>([]);form=signal<MarketAvailabilityRow|null>(null);
 statuses=['disabled','coming_soon','driver_onboarding','customer_beta','live','paused'];capabilityFields=[['customer_app_enabled','Customer app'],['customer_registration_enabled','Customer registration'],['driver_registration_enabled','Driver registration'],['driver_online_enabled','Driver online'],['quote_enabled','Quote'],['booking_enabled','Booking'],['payment_enabled','Payment'],['waiting_list_enabled','Waiting list']].map(([key,label])=>({key,label}));
 async ngOnInit(){await this.load();}async load(){this.rows.set(await this.api.list());}edit(row:MarketAvailabilityRow){this.form.set({...row});}create(){this.form.set({country_code:'',market_city:null,zone_id:null,launch_status:'coming_soon',supported_currency:null,timezone:null,enabled:true,waiting_list_enabled:true});}
 async save(){const row=this.form();if(!row)return;await this.api.save(row);this.form.set(null);await this.load();}}
