import {describe,expect,it} from 'vitest';
import {calculateCalendarAge,CANONICAL_DRIVER_PROFILE_SELECT,mapDriverProfile,parseDriverDateOfBirth,parseResidentialAddress} from '../../server/models/driver-profile.model';
import {DriverRequirementService} from '../../server/services/driver-requirement.service';
import {readFileSync} from 'node:fs';import {resolve} from 'node:path';
const route=readFileSync(resolve(process.cwd(),'server/routes/driver-onboarding.routes.ts'),'utf8');
const page=readFileSync(resolve(process.cwd(),'src/app/apps/mobile/features/driver/onboarding/onboarding.page.ts'),'utf8');
const driver=readFileSync(resolve(process.cwd(),'src/app/core/services/driver/driver.service.ts'),'utf8');

const row={id:'driver-1',full_name:'Alex Driver',phone:'07000000000',date_of_birth:'1990-01-01',current_address:'Unit 15, Groundwork Building, Oldham, OL1 4AW',verification_status:'incomplete'};
const resolveAddress=(profileRow:{[key:string]:unknown},confirmed=true)=>{const canonical=mapDriverProfile(profileRow as typeof row,confirmed);return DriverRequirementService.resolve({profile:{...profileRow,driver_service_types:[]},canonicalProfile:canonical,vehicle:null,authEmailConfirmed:confirmed});};

describe('canonical residential address',()=>{
 it('normalises and accepts a valid saved address',()=>expect(parseResidentialAddress({residentialAddress:`  ${row.current_address}  `})).toBe(row.current_address));
 it.each(['','   '])('rejects empty address %j',address=>expect(()=>parseResidentialAddress({residentialAddress:address})).toThrow('valid current residential'));
 it('maps the canonical current_address column',()=>expect(mapDriverProfile(row,true).residentialAddress).toBe(row.current_address));
 it('does not substitute vehicle or legacy fields for the canonical address',()=>expect(mapDriverProfile({...row,current_address:null},true).residentialAddress).toBeNull());
 it('marks profile.address complete from the persisted canonical profile',()=>expect(resolveAddress(row).automaticRequirements.find(item=>item.code==='profile.address')).toMatchObject({completed:true,status:'completed'}));
 it('leaves whitespace-only persisted addresses incomplete',()=>expect(resolveAddress({...row,current_address:'   '}).automaticRequirements.find(item=>item.code==='profile.address')?.completed).toBe(false));
 it('uses Supabase Auth confirmation for email status',()=>expect(resolveAddress(row,true).automaticRequirements.find(item=>item.code==='profile.email_verification')?.completed).toBe(true));
 it('does not trust a displayed email when Auth is unconfirmed',()=>expect(resolveAddress({...row,email:'driver@example.com'},false).automaticRequirements.find(item=>item.code==='profile.email_verification')?.completed).toBe(false));
 it('Save and Continue invokes authoritative setup persistence',()=>{expect(page).toContain('(click)="saveAndContinue()"');expect(page).toContain('await this.persistCurrentSetup()');expect(page).toContain('saveCurrentProfile({residentialAddress:address');});
 it('sends residentialAddress through the authenticated profile request',()=>expect(readFileSync(resolve(process.cwd(),'src/app/core/services/driver/driver-onboarding-status.service.ts'),'utf8')).toContain("'/api/driver-onboarding/profile',input,true"));
 it('persists scalar profile fields with the schema-safe projection and verifies the returned row',()=>{expect(route).toContain("profileUpdates:{current_address?:string;date_of_birth?:string;updated_at:string}");expect(route).toContain('select(CANONICAL_DRIVER_PROFILE_SELECT).single()');expect(route).toContain("residentialAddressPresent&&!profile.residentialAddress");expect(route).toContain("dateOfBirthPresent&&!profile.dateOfBirth");});
 it('selects only canonical profile columns after update',()=>{expect(CANONICAL_DRIVER_PROFILE_SELECT).toBe('id,full_name,phone,date_of_birth,current_address,verification_status,updated_at');expect(CANONICAL_DRIVER_PROFILE_SELECT).not.toContain('bicycle_declaration');});
 it('limits the profile update payload to scalar address and DOB metadata',()=>{const put=route.slice(route.indexOf("router.put('/profile'"),route.indexOf("router.put('/verification-items'"));expect(put).toContain("profileUpdates:{current_address?:string;date_of_birth?:string;updated_at:string}");expect(put).toContain('profileUpdates.current_address=parseResidentialAddress(body)');expect(put).toContain('profileUpdates.date_of_birth=parseDriverDateOfBirth(body.dateOfBirth)');expect(put).not.toContain('verification_items');expect(put).not.toContain('bicycle_declaration');expect(put).not.toContain('service_eligibility');expect(put).not.toContain('selected_services');});
 it('logs address payload keys without values',()=>expect(route).toContain("profile update payload',{userId:driverId,keys:Object.keys(profileUpdates)}"));
 it('writes declarations through the dedicated JSON-array path',()=>{const dedicated=route.slice(route.indexOf("router.put('/verification-items'"),route.indexOf("router.get('/vehicle'"));expect(dedicated).toContain('verification_items:serializeOnboardingItems(items)');expect(route).toContain('Array<{key:string;value:string}>');expect(page).toContain('await this.onboardingStatus.saveVerificationItems');});
 it('preserves bicycle declarations in onboarding verification data',()=>{const resolved=DriverRequirementService.resolve({profile:{...row,driver_service_types:['delivery'],verification_items:{bicycle_declaration:true,delivery_equipment_confirmed:true}},vehicle:{id:'bike',userId:'driver-1',type:'bike',make:null,model:null,colour:null,year:null,registrationNumber:null,capacity:'bike',serviceEligibility:['delivery'],status:'saved'},authEmailConfirmed:true});expect(resolved.automaticRequirements.find(item=>item.code==='vehicle.bicycle_declaration')?.completed).toBe(true);});
 it('surfaces PostgREST schema errors with their original code and diagnostics',()=>{expect(route).toContain("code:details.code||'PROFILE_SAVE_FAILED'");expect(route).toContain('details:details.details||null,hint:details.hint||null');});
 it('logs profile persistence presence without placing values in log metadata',()=>{expect(route).toContain("'[DriverOnboarding] profile update request'");expect(route).toContain('{userId:driverId,residentialAddressPresent,dateOfBirthPresent}');});
 it('loads and saves vehicles by authenticated user_id',()=>{expect(route).toContain(".eq('user_id',driverId)");expect(route).toContain('user_id:driverId');expect(driver).toContain('this.vehicle.set(saved)');});
 it('does not use local draft state to complete requirements',()=>expect(page).toContain('automaticRequirements.find(item=>item.blockingForSubmission)'));
 it('persists profile and vehicle before review submission',()=>{const persist=page.indexOf('const latestStatus=await this.persistCurrentSetup()');const submit=page.indexOf('await this.onboardingStatus.submitForReview');expect(persist).toBeGreaterThan(0);expect(submit).toBeGreaterThan(persist);expect(page.indexOf('saveCurrentProfile({residentialAddress:address')).toBeLessThan(page.indexOf('await this.driverService.updateVehicle',page.indexOf('private async persistCurrentSetup')));});
 it('reuses one refreshed authoritative status',()=>{const method=page.slice(page.indexOf('private async persistCurrentSetup'),page.indexOf('private restoreDraft'));expect(method.match(/onboardingStatus\.refresh\(\)/g)).toHaveLength(1);expect(page).toContain('latestStatus.automaticRequirements.filter');});
 it('does not submit after persistence failure',()=>{expect(page).toContain('const latestStatus=await this.persistCurrentSetup()');expect(page).toContain('catch {');expect(page).toContain('Your changes were not submitted. Please try again.');});
 it('submits review through the authenticated backend endpoint',()=>{expect(route).toContain("router.post('/submit-review'");expect(route).toContain("'[DriverOnboarding] review resubmission blocked'");});
});

describe('canonical driver date of birth',()=>{
 const now=new Date('2026-08-07T12:00:00Z');
 it('accepts ISO and normalises explicit DD/MM/YYYY input',()=>{expect(parseDriverDateOfBirth('1980-06-26',now)).toBe('1980-06-26');expect(parseDriverDateOfBirth('26/06/1980',now)).toBe('1980-06-26');});
 it('calculates exact eligible age',()=>expect(calculateCalendarAge('1980-06-26',now)).toBe(46));
 it('handles the birthday boundary exactly',()=>{expect(calculateCalendarAge('2008-08-08',now)).toBe(17);expect(calculateCalendarAge('2008-08-07',now)).toBe(18);});
 it.each(['not-a-date','31/02/1980','1980-13-01'])('rejects invalid date %s',date=>expect(()=>parseDriverDateOfBirth(date,now)).toThrow('valid date of birth'));
 it('rejects a future DOB',()=>expect(()=>parseDriverDateOfBirth('2027-01-01',now)).toThrow('future'));
 it('distinguishes missing, invalid, under-age and complete states',()=>{const requirement=(date:unknown)=>DriverRequirementService.resolve({profile:{...row,date_of_birth:date,driver_service_types:[]},canonicalProfile:mapDriverProfile({...row,date_of_birth:date as string},true),vehicle:null,authEmailConfirmed:true,now}).automaticRequirements.find(item=>item.code==='profile.date_of_birth');expect(requirement(null)).toMatchObject({status:'missing',reason:'Add your date of birth.'});expect(requirement('bad')).toMatchObject({status:'invalid',reason:'Enter a valid date of birth.'});expect(requirement('2015-02-14')).toMatchObject({status:'under_age',reason:'You must meet the minimum driver age requirement to register.'});expect(requirement('1980-06-26')).toMatchObject({status:'completed',completed:true});});
 it('converts DD/MM/YYYY explicitly before the authenticated API call',()=>{expect(page).toContain('const match=/^(\\d{2})\\/(\\d{2})\\/(\\d{4})$/.exec(raw)');expect(page).toContain('saveCurrentProfile({residentialAddress:address,dateOfBirth})');});
 it('updates local state only from the persisted canonical response',()=>{expect(page).toContain('date_of_birth:savedProfile.dateOfBirth');expect(page).toContain('this.formatDateForInput(savedProfile.dateOfBirth)');});
});
