const { Client } = require(process.env.MOVABI_PG_MODULE || 'pg');
class TestDatabase {
 constructor(){this.client=new Client({connectionString:process.env.MOVABI_TEST_DATABASE_URL});this.ready=this.client.connect();}
 async exec(sql){await this.ready;return this.client.query(sql);}
 async query(sql,args){await this.ready;return this.client.query(sql,args);}
 async close(){await this.client.end();}
}
const fs=require('fs'), assert=require('node:assert/strict');
const C='11111111-1111-4111-8111-111111111111',O='22222222-2222-4222-8222-222222222222',D='33333333-3333-4333-8333-333333333333';
const S='44444444-4444-4444-8444-444444444444',E='55555555-5555-4555-8555-555555555555';
let db,count=0;
const q=(sql,args=[])=>db.query(sql,args);
const row=async(sql,args)=>(await q(sql,args)).rows[0];
const balance=()=>row('SELECT available_balance::float8 AS a,reserved_balance::float8 AS r FROM wallets WHERE user_id=$1',[C]);
const state=id=>row('SELECT status,payment_status FROM jobs WHERE id=$1',[id]);
const call=(name,args)=>q(`SELECT public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) AS result`,args).then(r=>r.rows[0].result);
async function reset(){await db.exec('TRUNCATE wallet_transactions,errand_details,errand_funding,marketplace_negotiation_sessions,jobs,wallets,service_types CASCADE');await q("INSERT INTO wallets(user_id,available_balance,reserved_balance,currency_code) VALUES($1,100,0,'GBP'),($2,100,0,'GBP')",[C,O]);await q("INSERT INTO service_types(id,slug,name) VALUES($1,'delivery','Delivery'),($2,'errand','Errand')",[S,E]);}
async function job(opts={}){const id='aaaaaaaa-aaaa-4aaa-8aaa-'+String(++count).padStart(12,'0');const meta={quote_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',quote_expires_at:new Date(Date.now()+3600000).toISOString()};await q("INSERT INTO jobs(id,customer_id,driver_id,status,payment_status,service_type_id,total_price,estimated_price,price,currency_code,metadata,fare_breakdown,scheduled_time) VALUES($1,$2,$3,$4,'pending',$5,10,10,10,'GBP',$6,$7,$8)",[id,C,opts.driver||null,opts.status||'requested',opts.errand?E:S,JSON.stringify(meta),JSON.stringify({calculationVersion:'fixture-v1'}),opts.future?new Date(Date.now()+3600000).toISOString():null]);if(opts.errand)await q('INSERT INTO errand_details(job_id,estimated_budget) VALUES($1,20)',[id]);return id;}
const pay=id=>call('pay_job_from_wallet',[id,C,10,'GBP',null]);
async function rejects(fn,match){let caught=false;try{await fn();}catch(e){caught=true;if(match)assert.match(e.message,match);}assert(caught,'Expected rejection');}
async function test(name,fn){await reset();await fn();console.log('PASS '+name);}
(async()=>{
 db=new TestDatabase();await db.exec(fs.readFileSync(__dirname+'/fixture.sql','utf8'));await db.exec(fs.readFileSync(__dirname+'/migration.sql','utf8'));
 await test('payment activates search and reserves once',async()=>{const id=await job();await pay(id);assert.deepEqual(await balance(),{a:90,r:10});assert.deepEqual(await state(id),{status:'searching',payment_status:'wallet_funded'});await pay(id);assert.deepEqual(await balance(),{a:90,r:10});assert.equal((await row('SELECT count(*)::int AS n FROM wallet_transactions')).n,1);});
 await test('insufficient balance rolls back activation',async()=>{const id=await job();await q('UPDATE wallets SET available_balance=5 WHERE user_id=$1',[C]);await rejects(()=>pay(id),/Insufficient/);assert.equal((await state(id)).status,'requested');assert.deepEqual(await balance(),{a:5,r:0});});
 await test('expired quote causes no debit',async()=>{const id=await job();await q("UPDATE jobs SET metadata=jsonb_set(metadata,'{quote_expires_at}',to_jsonb('2000-01-01'::text)) WHERE id=$1",[id]);await rejects(()=>pay(id),/expired/);assert.deepEqual(await balance(),{a:100,r:0});});
 await test('unagreed Marketplace session rejects without debit',async()=>{const id=await job({status:'pending_fare_confirmation'});await q("INSERT INTO marketplace_negotiation_sessions(job_id,status) VALUES($1,'negotiating')",[id]);await rejects(()=>pay(id),/agreement_lost/);assert.deepEqual(await balance(),{a:100,r:0});assert.equal((await state(id)).status,'pending_fare_confirmation');});
 await test('valid agreed driver activates assigned and preserves fare',async()=>{const id=await job({status:'fare_agreed',driver:D});await q('UPDATE jobs SET agreed_fare=9 WHERE id=$1',[id]);await q("INSERT INTO marketplace_negotiation_sessions(job_id,status,agreed_fare,active_driver_id,payment_deadline) VALUES($1,'fare_agreed',9,$2,now()+interval '5 minutes')",[id,D]);await call('pay_job_from_wallet',[id,C,9,'GBP',null]);assert.equal((await state(id)).status,'assigned');assert.deepEqual(await balance(),{a:91,r:9});});
 await test('expired agreement rolls back wallet',async()=>{const id=await job({status:'fare_agreed',driver:D});await q('UPDATE jobs SET agreed_fare=10 WHERE id=$1',[id]);await q("INSERT INTO marketplace_negotiation_sessions(job_id,status,agreed_fare,active_driver_id,payment_deadline) VALUES($1,'fare_agreed',10,$2,now()-interval '1 minute')",[id,D]);await rejects(()=>pay(id),/agreement_expired/);assert.deepEqual(await balance(),{a:100,r:0});});
 await test('scheduled paid booking waits for due time',async()=>{const id=await job({future:true});await pay(id);assert.equal((await state(id)).status,'requested');assert.equal((await row('SELECT dispatch_started_at FROM jobs WHERE id=$1',[id])).dispatch_started_at,null);});
 await test('wrong customer/currency/amount/tenant cannot debit',async()=>{const id=await job();for(const args of [[id,O,10,'GBP',null],[id,C,10,'USD',null],[id,C,-10,'GBP',null],[id,C,9,'GBP',null],[id,C,10,'GBP',O]])await rejects(()=>call('pay_job_from_wallet',args));assert.deepEqual(await balance(),{a:100,r:0});});
 await test('cancel and repeat release return exactly the reservation',async()=>{const id=await job();await pay(id);await call('cancel_job_safely',[id,'Test']);await call('cancel_job_safely',[id,'Repeat']);assert.deepEqual(await balance(),{a:100,r:0});assert.deepEqual(await state(id),{status:'cancelled',payment_status:'cancelled'});assert.equal((await row("SELECT count(*)::int AS n FROM wallet_transactions WHERE transaction_type='release'")).n,1);await rejects(()=>pay(id),/status/);});
 await test('cancellation handles fare-confirmation state',async()=>{const id=await job({status:'pending_fare_confirmation'});assert.equal(await call('cancel_job_safely',[id,'Test']),true);assert.equal((await state(id)).status,'cancelled');});
 await test('timeout ends search and releases atomically once',async()=>{const id=await job();await pay(id);await q("UPDATE jobs SET dispatch_attempts=3,driver_search_expires_at=now()-interval '1 minute' WHERE id=$1",[id]);await call('end_job_driver_search',[id]);await call('end_job_driver_search',[id]);assert.deepEqual(await balance(),{a:100,r:0});assert.deepEqual(await state(id),{status:'no_driver_found',payment_status:'cancelled'});});
 await test('timeout cannot end a newly assigned booking',async()=>{const id=await job();await pay(id);await q("UPDATE jobs SET driver_id=$2,status='assigned',dispatch_attempts=3,driver_search_expires_at=now()-interval '1 minute' WHERE id=$1",[id,D]);assert.equal(await call('end_job_driver_search',[id]),null);assert.deepEqual(await balance(),{a:90,r:10});});
 await test('failed release rolls back terminal transition',async()=>{const id=await job();await pay(id);await q('UPDATE wallets SET reserved_balance=0 WHERE user_id=$1',[C]);await rejects(()=>call('cancel_job_safely',[id,'Test']),/inconsistent/);assert.equal((await state(id)).status,'searching');await q("UPDATE jobs SET dispatch_attempts=3,driver_search_expires_at=now()-interval '1 minute' WHERE id=$1",[id]);await rejects(()=>call('end_job_driver_search',[id]),/inconsistent/);assert.equal((await state(id)).status,'searching');});
 await test('errand fare and budget reserve once, release all',async()=>{const id=await job({errand:true});await call('pay_job_from_wallet',[id,C,30,'GBP',null]);assert.deepEqual(await balance(),{a:70,r:30});const f=await row('SELECT item_budget::float8 AS b,service_estimate::float8 AS f,amount_reserved::float8 AS t FROM errand_funding');assert.deepEqual(f,{b:20,f:10,t:30});await call('cancel_job_safely',[id,'Test']);assert.deepEqual(await balance(),{a:100,r:0});});
 await test('settlement charges fare plus spend, releases unused budget once',async()=>{const id=await job({errand:true});await call('pay_job_from_wallet',[id,C,30,'GBP',null]);await q("UPDATE jobs SET driver_id=$2,status='shopping_in_progress' WHERE id=$1",[id,D]);await q('UPDATE errand_details SET actual_spending=12 WHERE job_id=$1',[id]);const a=await call('settle_job_wallet_reservation',[id,10]);assert.equal(a.amount_settled,22);assert.equal(a.amount_released,8);await call('settle_job_wallet_reservation',[id,10]);assert.deepEqual(await balance(),{a:78,r:0});assert.equal(await call('cancel_job_safely',[id,'Test']),false);assert.deepEqual(await balance(),{a:78,r:0});});
 await test('non-errand settlement retry does not debit again',async()=>{const id=await job();await pay(id);await call('settle_job_wallet_reservation',[id,10]);assert.equal((await call('settle_job_wallet_reservation',[id,10])).status,'already_settled');assert.deepEqual(await balance(),{a:90,r:0});});
 await test('overspend fails closed with reservation intact',async()=>{const id=await job({errand:true});await call('pay_job_from_wallet',[id,C,30,'GBP',null]);await q('UPDATE errand_details SET actual_spending=25 WHERE job_id=$1',[id]);await rejects(()=>call('settle_job_wallet_reservation',[id,10]),/exceeds/);assert.deepEqual(await balance(),{a:70,r:30});});
 await test('budget approval reserves positive delta once and settles approved spend',async()=>{const id=await job({errand:true});await call('pay_job_from_wallet',[id,C,30,'GBP',null]);await q("UPDATE jobs SET driver_id=$2,status='shopping_in_progress' WHERE id=$1",[id,D]);await call('request_errand_over_budget',[id,25,'More groceries']);await call('approve_errand_over_budget',[id]);await call('approve_errand_over_budget',[id]);assert.deepEqual(await balance(),{a:65,r:35});await q('UPDATE errand_details SET actual_spending=25 WHERE job_id=$1',[id]);await call('settle_job_wallet_reservation',[id,10]);assert.deepEqual(await balance(),{a:65,r:0});});
 await test('legacy settlement entry point uses job_id and canonical ledger',async()=>{const id=await job({errand:true});await call('pay_job_from_wallet',[id,C,30,'GBP',null]);await call('settle_errand_funds',[id]);await call('settle_errand_funds',[id]);assert.deepEqual(await balance(),{a:90,r:0});});
 await test('concurrent retries reserve one time',async()=>{const id=await job();await Promise.all([pay(id),pay(id)]);assert.deepEqual(await balance(),{a:90,r:10});assert.equal((await row("SELECT count(*)::int AS n FROM wallet_transactions WHERE transaction_type='reservation'")).n,1);});
 await test('two jobs cannot overspend one wallet',async()=>{const a=await job(),b=await job();await q('UPDATE wallets SET available_balance=15 WHERE user_id=$1',[C]);const r=await Promise.allSettled([pay(a),pay(b)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.deepEqual(await balance(),{a:5,r:10});});
 await test('payment and cancellation race preserves funds',async()=>{const id=await job();await Promise.allSettled([pay(id),call('cancel_job_safely',[id,'Race'])]);assert.deepEqual(await balance(),{a:100,r:0});assert.equal((await state(id)).status,'cancelled');});
 await test('settlement and cancellation cannot both move funds',async()=>{const id=await job({driver:D});await pay(id);await Promise.allSettled([call('settle_job_wallet_reservation',[id,10]),call('cancel_job_safely',[id,'Race'])]);const b=await balance();const st=await state(id);assert.equal(b.r,0);assert((st.status==='cancelled'&&b.a===100)||(st.payment_status==='paid'&&b.a===90));});
 await test('release ledger insert failure rolls cancellation back',async()=>{const id=await job();await pay(id);await db.exec("CREATE FUNCTION test_fail_release() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.transaction_type='release' THEN RAISE EXCEPTION 'Injected ledger failure'; END IF; RETURN NEW; END $$; CREATE TRIGGER test_fail_release BEFORE INSERT ON wallet_transactions FOR EACH ROW EXECUTE FUNCTION test_fail_release();");await rejects(()=>call('cancel_job_safely',[id,'Test']),/Injected/);assert.deepEqual(await balance(),{a:90,r:10});assert.equal((await state(id)).status,'searching');await db.exec('DROP TRIGGER test_fail_release ON wallet_transactions;DROP FUNCTION test_fail_release()');});
 await test('reservation ledger insert failure rolls activation back',async()=>{const id=await job();await db.exec("CREATE FUNCTION test_fail_reservation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Injected reservation failure'; END $$; CREATE TRIGGER test_fail_reservation BEFORE INSERT ON wallet_transactions FOR EACH ROW EXECUTE FUNCTION test_fail_reservation();");await rejects(()=>pay(id),/Injected/);assert.deepEqual(await balance(),{a:100,r:0});assert.equal((await state(id)).status,'requested');await db.exec('DROP TRIGGER test_fail_reservation ON wallet_transactions;DROP FUNCTION test_fail_reservation()');});
 await test('another customer cannot approve budget',async()=>{const id=await job({errand:true});await call('pay_job_from_wallet',[id,C,30,'GBP',null]);await q("UPDATE jobs SET driver_id=$2,status='shopping_in_progress' WHERE id=$1",[id,D]);await call('request_errand_over_budget',[id,25,'More groceries']);try{await rejects(()=>db.exec("SET SESSION AUTHORIZATION authenticator;SET ROLE authenticated;SELECT set_config('test.user','"+O+"',false);SELECT set_config('test.role','authenticated',false);SELECT approve_errand_over_budget('"+id+"');"),/Only the customer/);}finally{await db.exec('SET SESSION AUTHORIZATION postgres;SET ROLE postgres');}assert.deepEqual(await balance(),{a:70,r:30});});
 await test('another driver cannot request budget',async()=>{const id=await job({errand:true});await call('pay_job_from_wallet',[id,C,30,'GBP',null]);await q("UPDATE jobs SET driver_id=$2,status='shopping_in_progress' WHERE id=$1",[id,D]);try{await rejects(()=>db.exec("SET SESSION AUTHORIZATION authenticator;SET ROLE authenticated;SELECT set_config('test.user','"+O+"',false);SELECT set_config('test.role','authenticated',false);SELECT request_errand_over_budget('"+id+"',25,'More groceries');"),/Only the assigned/);}finally{await db.exec('SET SESSION AUTHORIZATION postgres;SET ROLE postgres');}assert.deepEqual(await balance(),{a:70,r:30});});
 await test('financial RPCs deny anon and authenticated',async()=>{const r=await q("SELECT p.proname,has_function_privilege('anon',p.oid,'EXECUTE') AS a,has_function_privilege('authenticated',p.oid,'EXECUTE') AS u,has_function_privilege('service_role',p.oid,'EXECUTE') AS s FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname IN ('pay_job_from_wallet','release_job_wallet_reservation','reserve_errand_funds','settle_errand_funds','settle_job_wallet_reservation','cancel_job_safely','end_job_driver_search')");assert.equal(r.rows.length,7);for(const x of r.rows){assert.equal(x.a,false,x.proname);assert.equal(x.u,false,x.proname);assert.equal(x.s,true,x.proname);}});
 console.log('DATABASE_LIFECYCLE_TESTS=PASS');await db.close();
})().catch(e=>{console.error(e);process.exit(1)});
